FbNaukowcy/urls.py
from django.urls import path
from . import views

app_name = 'FbNaukowcy'
urlpatterns = [
    path('', views.publication_list, name='publication_list'),
    path('projects/',views.project_list, name='project_list'),
    path('projects/add/', views.add_project, name='add_project'),
    path('add/', views.add_publication, name='add_publication'),
    path('projects/<int:project_id>/rounds', views.rounds, name='founding_rounds'),
    path('projects/<int:project_id>', views.project_details, name='project_details'), 
    path('projects/<int:project_id>/create_invitation', views.create_invitation, name='create_invitation'),
    path('papers/<int:publication_id>', views.publication_details, name='publication_details'), 
]

auth_app/urls.py
from django.urls import path
from .views import login_view, logout_view, secured_view, register_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('secured_example/', secured_view, name='secured'),
]

django_main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('scientist_feed/', include('FbNaukowcy.urls')),

    path('', include('auth_app.urls')),

    path('', include('start_page.urls')),

    path('buisness/', include('BuissnessSearch.urls')),
]

FbNaukowcy/forms.py
from django import forms
from common.models import Invitation, Paper, Project, FinanceRound

class FinanceRoundForm(forms.ModelForm):
    class Meta:
        model = FinanceRound
        fields = ['title', 'brief', 'fundings_gathered', 'end_date']
        widgets = {
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

class PublicationForm(forms.ModelForm):
    class Meta:
        model = Paper
        fields = ['title', 'brief','link']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'brief': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Content'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Link'}),
        }

    def __init__(self, *args, **kwargs):
        # Extract the 'user' parameter from the keyword arguments
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:  # Assign the user to the instance
            instance.user = self.user
        if commit:
            instance.save()
        return instance

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['title', 'brief','is_public','content','required_money','type','project_scope']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tytuł'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Szczegółowy opis'}),
            'brief': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Krótki opis'}),
            'project_scope': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Zakres projektu'}), 
            'is_public': forms.CheckboxInput(),
            'type': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            # 'profiles': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Get the user from the view
        super().__init__(*args, **kwargs)

        if user:
            # Set the initial value for the author field to the logged-in user
            self.fields['author'] = forms.CharField(initial=user.profile_set,
                                                    widget=forms.HiddenInput())  # You can make it hidden or display it
            self.instance.author = user  # Set the author when saving the instance
    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:  # Assign the user to the instance
            instance.user = self.user
        if commit:
            instance.save()
        return instance

FbNaukowcy/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from common.models import CustomUser, Paper, Profile, Project, FinanceRound
from common.models import CustomUser, Invitation, Paper, Profile, Project
from .forms import FinanceRoundForm, PublicationForm, ProjectForm
from django.contrib.auth.decorators import login_required

@login_required
def publication_list(request):
    logged_user = request.user
    # publications = Paper.objects.all()
    publications_of_logged_user = Paper.objects.filter(author__user=logged_user)
    publications_of_other_users = Paper.objects.exclude(author__user=logged_user)
    users = CustomUser.objects.all()
    is_scientist = logged_user.profile_set.filter(type='scientist').exists()
    return render(request, 'FbNaukowcy/publication_list.html',
                  {'publications_of_logged_user': publications_of_logged_user, 'publications_of_other_users': publications_of_other_users, 'users': users, 'logged_user': logged_user, 'is_scientist': is_scientist})

@login_required
def project_list(request):
    logged_user = request.user

    logged_user_projects = [ ]
    for profile in logged_user.profile_set.all():
        for project in profile.projects.all():
            logged_user_projects.append(project)

    projects = Project.objects.all()
    other_projects = [ ]
    for project in projects:
        if not project in logged_user_projects:
            other_projects.append(project)

    invitations = Invitation.objects.filter(receiver__user=logged_user)
    users = Profile.objects.all()
    return render(request, 'FbNaukowcy/projects_list.html',
                  {'publications': other_projects, 'users': users, 'invitations': invitations, 'logged_user': logged_user, 'your_projects': logged_user_projects})

@login_required
def add_publication(request):
    if request.method == 'POST':
        form = PublicationForm(request.POST,user=request.user)
        if form.is_valid():
            form.save()
            return redirect('FbNaukowcy:publication_list')  # Przekierowanie na listę postów
    else:
        form = PublicationForm()
    return render(request, 'FbNaukowcy/add_publication.html', {'form': form})

def project_details(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    rounds = FinanceRound.objects.filter(project=project)
    return render(request, 'FbNaukowcy/project_details.html', {'project': project, 'rounds': rounds})

def publication_details(request, publication_id):
    paper = get_object_or_404(Paper, pk=publication_id)
    return render(request, 'FbNaukowcy/publication_details.html', {'paper': paper})


def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST,user=request.user)
        if form.is_valid():
            form.save()
            return redirect('projects_list')  # Przekierowanie na listę postów
    else:
        form = ProjectForm()
    return render(request, 'FbNaukowcy/add_project.html', {'form': form})

@login_required
def rounds(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = FinanceRoundForm(request.POST)
        if form.is_valid():
            finance_round = form.save(commit=False)
            finance_round.project = project
            finance_round.save()
            return redirect('project_details', project_id=project_id)
    else:
        form = FinanceRoundForm()
    return render(request, 'FbNaukowcy/add_round.html', {'form': form, 'project': project})

@login_required
def create_invitation(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    username = request.user
    user = get_object_or_404(CustomUser, username=username)
    profile = user.profile_set.first()
    if request.method == 'POST':
        invitation = Invitation.objects.create(
            project=project,
            sender = profile,
            receiver = CustomUser.objects.get(username=request.POST['receiver']).profile_set.first(),
            status = 'pending',
            message=request.POST['message'])
        invitation.save()
    return render(request, 'FbNaukowcy/create_invitation.html', {})

FbNaukowcy/templates/FbNaukowcy/add_project.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Project</title>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            background-color: #F6F6F6;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header {
            padding-top: 20px;
            margin-left: auto;
            margin-right: auto;
            width: 96%;
        }

        header a {
            text-decoration: none;
            color: #274C77;
        }

        .container {
            display: flex;
            flex: 1;
        }

        nav {
            width: 15%;
            padding: 20px;
        }

        nav a {
            display: block;
            margin-bottom: 10px;
            text-decoration: none;
            color: #007bff;
        }

        main {
            flex: 1;
            padding: 20px;
        }

        h2 {
            color: #274C77;
            margin-bottom: 20px;
        }

        .btn {
            padding: 12px 24px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
            background: #274C77;
            color: white;
        }

        .btn:hover {
            background: white;
            color: #274C77;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        .tile {
            display: inline-block;
            width: 20%;
            height: 200px;
            padding: 20px;
            border: 1px solid #274C77;
            background: #F6F6F6;
            color: #274C77;
            vertical-align: top;
            transition: all 0.3s ease;
            margin-right: 50px;
            margin-bottom: 50px;
        }

        main h2 {
            padding-bottom: 30px;
        }

        .arrow-link {
            position: relative;
            color: #274C77;
            text-decoration: none;
        }

        .tile:hover .arrow-link {
            color: white;
        }

        #add_publication {
            position: fixed;
            display: block;
            background: #274C77;
            color: white;
            text-decoration: none;
            transition: all 0.3s ease;
            bottom: 20px;
            left: 20px;
            text-align: center;
            border: 1px solid #274C77;
        }

        #add_publication:hover {
            background: white;
            color: #274C77;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            background-color: #F6F6F6;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header {
            padding-top: 20px;
            margin-left: auto;
            margin-right: auto;
            width: 96%;
        }

        header a {
            text-decoration: none;
            color: #274C77;
        }

        .container {
            display: flex;
            flex: 1;
        }

        nav {
            width: 15%;
            padding: 20px;
        }

        nav a {
            display: block;
            margin-bottom: 10px;
            text-decoration: none;
            color: #007bff;
        }

        main {
            flex: 1;
            padding: 20px;
        }

        h2 {
            color: #274C77;
            margin-bottom: 20px;
        }

        .btn {
            padding: 12px 24px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
            background: #274C77;
            color: white;
        }

        .btn:hover {
            background: white;
            color: #274C77;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        .tile {
            display: inline-block;
            width: 20%;
            height: 200px;
            padding: 20px;
            border: 1px solid #274C77;
            background: #F6F6F6;
            color: #274C77;
            vertical-align: top;
            transition: all 0.3s ease;
            margin-right: 50px;
            margin-bottom: 50px;
        }

        main h2 {
            padding-bottom: 30px;
        }

        .arrow-link {
            position: relative;
            color: #274C77;
            text-decoration: none;
        }

        .tile:hover .arrow-link {
            color: white;
        }

        #add_publication {
            position: fixed;
            display: block;
            background: #274C77;
            color: white;
            text-decoration: none;
            transition: all 0.3s ease;
            bottom: 20px;
            left: 20px;
            text-align: center;
            border: 1px solid #274C77;
        }

        #add_publication:hover {
            background: white;
            color: #274C77;
        }

        p:has(.form-control) {
            display: flex;
            flex-direction: column;
        }
    </style>

</head>

<body>
    <header>
        <div id="title">
            <h1><a href="/">trAIcon</a></h1>
        </div>
    </header>
    <div class="container">
        <nav>
            <a href="/" class="btn">Strona Główna</a>
            <a href="{% url 'FbNaukowcy:project_list' %}" class="btn">Projekty</a>
        </nav>
        <main>
            <h1>Dodaj nowy projekt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Zapisz</button>
            </form>
        </main>
    </div>
</body>

</html>

FbNaukowcy/templates/FbNaukowcy/add_publication.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Paper</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Montserrat', sans-serif;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            background-color: #F6F6F6;
            height: 100vh;
        }

        #title {
            padding-left: 2%;
            padding-top: 20px;
        }

        #title a {
            text-decoration: none;
            color: #274C77;
        }

        #content {
            margin: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            padding: 20px;
        }

        h2 {
            color: #274C77;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #274C77;
            box-sizing: border-box;
        }

        .form-group textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #274C77;
            box-sizing: border-box;
        }

        .form-group button {
            margin-top: 20px;
            width: 100%;
            height: 50px;
            padding: 10px;
            background-color: #274C77;
            color: white;
            border: none;
            cursor: pointer;
            box-sizing: border-box;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
        }

        .form-group button:hover {
            background: white;
            color: #274C77;
        }

        .form-group p {
            margin-top: 10px;
        }

        .form-group p a {
            color: #6096BA;
            text-decoration: none;
            margin-top: 5px;
        }

        .form-group p a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <div id="title">
        <h1><a href="/">trAIcon</a></h1>
    </div>
    <div id="content">
        <form method="post" class="form-group">
            <h2>Stwórz nową pracę projektową</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Zapisz</button>
            <a href="{% url 'FbNaukowcy:publication_list' %}">Wróć do projektu</a>
        </form>
    </div>
</body>

</html>

FbNaukowcy/templates/FbNaukowcy/projects_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publication List</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            background-color: #F6F6F6;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header {
            padding-top: 20px;
            margin-left: auto;
            margin-right: auto;
            width: 96%;
        }

        header a {
            text-decoration: none;
            color: #274C77;
        }

        .container {
            display: flex;
            flex: 1;
        }

        nav {
            width: 21vw;
            padding: 20px;
            margin-right: 50px;
            margin-top: 30px;
        }

        nav a {
            display: block;
            margin-bottom: 10px;
            text-decoration: none;
            color: #007bff;
        }

        main {
            flex: 1;
            padding: 20px;
        }

        h2 {
            color: #274C77;
            margin-bottom: 20px;
        }

        .btn {
            padding: 17px 24px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
            background: #274C77;
            color: white;
            border-radius: 10px;
            font-size: 14px;
            font-weight: 500;
        }

        .btn:hover {
            background: white;
            color: #274C77;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        .tile {
            display: inline-block;
            width: 300px;
            height: 200px;
            padding: 20px;
            border: 1px solid #274C77;
            background: #F6F6F6;
            color: #274C77;
            vertical-align: top;
            transition: all 0.3s ease;
            margin-right: 50px;
            margin-bottom: 50px;
        }

        main h2 {
            padding-bottom: 5px;
        }

        .arrow-link {
            position: relative;
            color: #274C77;
            text-decoration: none;
        }

        .tile:hover .arrow-link {
            color: white;
        }

        #add_publication {
            position: fixed;
            display: block;
            background: #274C77;
            color: white;
            text-decoration: none;
            transition: all 0.3s ease;
            bottom: 20px;
            left: 20px;
            text-align: center;
            border: 1px solid #274C77;
        }

        #add_publication:hover {
            background: white;
            color: #274C77;
        }

        .bottom-left-buttons {
            position: fixed;
            bottom: 20px;
            left: 20px;
            display: flex;
            gap: 10px;
        }

        .bottom-left-buttons .btn {
            background: #274C77;
            color: white;
            text-decoration: none;
            padding: 10px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
        }

        .bottom-left-buttons .btn:hover {
            background: white;
            color: #274C77;
        }

        #scientist_button {
            background: white;
            color: #274C77;
            padding: 10px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
        }

        main a {
            text-decoration: none;
            color: #274C77;
        }

        main a:hover {
            color: #274C77;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <header>
        <div id="title">
            <h1><a href="/">trAIcon</a></h1>
        </div>
    </header>
    <div class="container">
        <nav>
            <a href="/" class="btn">Strona Główna</a>
            <a href="{% url 'FbNaukowcy:publication_list' %}" class="btn">Prace Naukowe</a>
        </nav>
        <main>
            <h2>Twoje Projekty</h2>
            <ul>
                {% for post in your_projects %}
                <li class="tile">
                    <a href="{% url 'FbNaukowcy:project_details' post.pk %}">
                        <div>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.brief|truncatewords:20 }}</p>
                            <small>Posted by {{ post.user.username }} on {{ post.created_at }}</small>
                        </div>
                    </a>
                </li>
                {% empty %}
                <li>No posts available.</li>
                {% endfor %}
            </ul>
            <h2>Dostępne Projekty</h2>
            <ul>
                {% for post in publications %}
                <li class="tile">
                    <a href="{% url 'FbNaukowcy:project_details' post.pk %}">
                        <div>
                            <h3>{{ post.title }}</h3>
                            <p>{{ post.brief|truncatewords:20 }}</p>
                            <small>Posted by {{ post.user.username }} on {{ post.created_at }}</small>
                        </div>
                    </a>
                </li>
                {% empty %}
                <li>No posts available.</li>
                {% endfor %}
            </ul>
            <h2>Zaproszenia</h2>
            <ul>
                {% for invitation in invitations %}
                <li class="tile">
                    <h3>{{ invitation.project.title }}</h3>
                    <p>{{ invitation.brief|truncatewords:20 }}</p>
                    <small>Jesteś zaproszony przez {{ invitation.sender.user.username }} by dołączyć do projektu o
                        nazwie {{ invitation.project.title }}.</small>
                </li>
                {% empty %}
                <li>Brak oczekujących zaproszeń.</li>
                {% endfor %}
            </ul>
        </main>
    </div>
</body>

</html>

FbNaukowcy/templates/FbNaukowcy/publication_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publication List</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            background-color: #F6F6F6;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        header {
            padding-top: 20px;
            margin-left: auto;
            margin-right: auto;
            width: 96%;
        }

        header a {
            text-decoration: none;
            color: #274C77;
        }

        .container {
            display: flex;
            flex: 1;
        }

        nav {
            width: 21vw;
            padding: 20px;
            margin-right: 50px;
            margin-top: 30px;
        }

        nav a {
            display: block;
            margin-bottom: 10px;
            text-decoration: none;
            color: #007bff;
        }

        main {
            flex: 1;
            padding: 20px;
        }

        h2 {
            color: #274C77;
            margin-bottom: 0px;
        }

        .btn {
            padding: 17px 24px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
            background: #274C77;
            color: white;
            border-radius: 10px;
            font-size: 14px;
            font-weight: 500;
        }

        .btn:hover {
            background: white;
            color: #274C77;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        .tile {
            display: inline-block;
            width: 300px;
            height: 200px;
            padding: 20px;
            border: 1px solid #274C77;
            background: #F6F6F6;
            color: #274C77;
            vertical-align: top;
            transition: all 0.3s ease;
            margin-right: 50px;
            margin-bottom: 50px;
        }

        main h2 {
            padding-bottom: 30px;
        }

        .arrow-link {
            position: relative;
            color: #274C77;
            text-decoration: none;
        }

        .tile:hover .arrow-link {
            color: white;
        }

        #add_publication {
            display: block;
            background: #274C77;
            color: white;
            text-decoration: none;
            transition: all 0.3s ease;
            bottom: 80px;
            left: 20px;
            border: 1px solid #274C77;
            width: 100%;
        }

        #add_publication:hover {
            background: white;
            color: #274C77;
        }

        .bottom-left-buttons {
            position: fixed;
            bottom: 20px;
            left: 20px;
            display: flex;
            gap: 10px;
        }

        .bottom-left-buttons .btn {
            background: #274C77;
            color: white;
            text-decoration: none;
            padding: 10px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
        }

        .bottom-left-buttons .btn:hover {
            background: white;
            color: #274C77;
        }

        #scientist_button {
            background: white;
            color: #274C77;
            padding: 10px;
            border: 1px solid #274C77;
            transition: all 0.3s ease;
        }

        main a {
            text-decoration: none;
            color: #274C77;
        }
    </style>
</head>

<body>
    <header>
        <div id="title">
            <h1><a href="/">trAIcon</a></h1>
        </div>
    </header>
    <div class="container">
        <nav>
            <a href="/" class="btn">Strona Główna</a>
            {% if is_scientist %}
            <a href="{% url 'FbNaukowcy:project_list' %}" class="btn btn-primary">Zobacz projekty</a>
            <a id="add_publication" class="btn" href="{% url 'FbNaukowcy:add_publication' %}">Stwórz pracę naukową</a>
            {% else %}
            {% endif %}
        </nav>
        <main>
            <!-- TODO provide publications from the database -->
            <h2>Prace naukowe</h2>
            <h2>Publikacje dla Ciebie</h2>
            <ul>
                {% for publication in publications_of_other_users %}
                <li class="tile">
                    <a href="{% url 'FbNaukowcy:publication_details' publication.id %}">
                        <div>
                            <h3>{{ publication.title }}</h3>
                            <p>{{ publication.brief|truncatewords:20 }}</p>
                            <small>Posted by {{ publication.user.username }} on {{ publication.created_at }}</small>
                        </div>
                    </a>
                </li>
                {% empty %}
                <li>No posts available.</li>
                {% endfor %}
            </ul>
            <h2>Twoje otwarte projekty naukowe</h2>
            <ul>
                {% for publication in publications_of_logged_user %}
                <li class="tile">
                    <a href="{% url 'FbNaukowcy:publication_details' publication.id %}">
                        <div>
                            <h3>{{ publication.title }}</h3>
                            <p>{{ publication.brief|truncatewords:20 }}</p>
                            <small>Posted by {{ publication.user.username }} on {{ publication.created_at }}</small>
                        </div>
                    </a>
                </li>
                {% empty %}
                <li>No posts available.</li>
                {% endfor %}
                <!-- <li class="tile">
                        <h3>Lorem, ipsum.</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae facere suscipit reiciendis voluptatum ut saepe quibusdam impedit tempore architecto totam.</p>
                        <small>Autorzy</small>
                        <a href="link-to-post" class="arrow-link"><i class="fas fa-arrow-right"></i></a>
                    </li>
                    <li class="tile">
                        <h3>Lorem, ipsum.</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae facere suscipit reiciendis voluptatum ut saepe quibusdam impedit tempore architecto totam.</p>
                        <small>Autorzy</small>
                        <a href="link-to-post" class="arrow-link"><i class="fas fa-arrow-right"></i></a>
                    </li>
                    <li class="tile">
                        <h3>Lorem, ipsum.</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae facere suscipit reiciendis voluptatum ut saepe quibusdam impedit tempore architecto totam.</p>
                        <small>Autorzy</small>
                        <a href="link-to-post" class="arrow-link"><i class="fas fa-arrow-right"></i></a>
                    </li>
                    <li class="tile">
                        <h3>Lorem, ipsum.</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae facere suscipit reiciendis voluptatum ut saepe quibusdam impedit tempore architecto totam.</p>
                        <small>Autorzy</small>
                        <a href="link-to-post" class="arrow-link"><i class="fas fa-arrow-right"></i></a>
                    </li> -->
            </ul>
        </main>
    </div>
</body>

</html>